### ISSUE TITLE
AML Workspace  version

### ISSUE THREAD

**Issue by indcoder** [GlobalAICommunity/Workshop-VisualInterfaceAzureMLSWine#3]
In the first step of creating the Machine Learning configuration, a screen shot is required because

1.  Not all regions have the ML resource; so some guidance here for attendees would be helpful

2. It is silent over what version of the workspace to be choses : Basic or  Enterprise....and when we should opt for each of them

Most attendees for the bootcamp with a mere $50 Azure pass would opt for the cheaper Basic version but that will lead to designer getting locked 👇
![image](https://user-images.githubusercontent.com/2099300/70698579-c9ff4c80-1ced-11ea-8715-ae3fa5234dec.png)

**Comment by mdragt** [comment]
Thanks for letting us know! The workspace should be enterprise indeed, added that.
