### ISSUE TITLE
qualityBool should be removed : text is unlcear

### ISSUE THREAD

**Issue by indcoder** [GlobalAICommunity/Workshop-VisualInterfaceAzureMLSWine#4]
The below text is ambiguous . There should be a clear directive text....either qualityBool has to be removed or not?

Enhance the rule, indicating that you also want to exclude the variable qualityBool

![image](https://user-images.githubusercontent.com/2099300/70719844-c503c280-1d18-11ea-84bb-6b7a762def35.png)

**Comment by mdragt** [comment]
Hi indcoder, this is for the predictive model and as such, the dependent variable should be removed.
