### ISSUE TITLE
The text says to remove Evaluate model but the subsequent image still contains it

### ISSUE THREAD

**Issue by indcoder** [GlobalAICommunity/Workshop-VisualInterfaceAzureMLSWine#5]
The instructions in the text do not manifest themselves in the subsequent image  : Evaluate Model is being shown in the followup image even though the text above the pic directs the user to do the opposite.

![image](https://user-images.githubusercontent.com/2099300/70721298-54aa7080-1d1b-11ea-8bd2-74e0f297c42c.png)

**Comment by mdragt** [comment]
Thanks for letting us know! This step is optional, and i updated the instructions.
